export function getCountries() {
  return [
    {
      name: 'Deutschland',
      code: 'DE',
      flagUrl: '/flags/de.svg',
      regions: [
        'Baden-Württemberg',
        'Bayern',
        'Berlin',
        'Brandenburg',
        'Bremen',
        'Hamburg',
        'Hessen',
        'Mecklenburg-Vorpommern',
        'Niedersachsen',
        'Nordrhein-Westfalen',
        'Rheinland-Pfalz',
        'Saarland',
        'Sachsen',
        'Sachsen-Anhalt',
        'Schleswig-Holstein',
        'Thüringen',
      ],
    },
    {
      name: 'Schweiz',
      code: 'CH',
      flagUrl: '/flags/ch.svg',
      regions: [
        'Aargau',
        'Appenzell Ausserrhoden',
        'Appenzell Innerrhoden',
        'Basel-Landschaft',
        'Basel-Stadt',
        'Bern',
        'Freiburg',
        'Genf',
        'Glarus',
        'Graubünden',
        'Jura',
        'Luzern',
        'Neuenburg',
        'Nidwalden',
        'Obwalden',
        'Schaffhausen',
        'Schwyz',
        'Solothurn',
        'St. Gallen',
        'Tessin',
        'Thurgau',
        'Uri',
        'Waadt',
        'Wallis',
        'Zug',
        'Zürich',
      ],
    },
    {
      name: 'Österreich',
      code: 'AT',
      flagUrl: '/flags/at.svg',
      regions: [
        'Burgenland',
        'Kärnten',
        'Niederösterreich',
        'Oberösterreich',
        'Salzburg',
        'Steiermark',
        'Tirol',
        'Vorarlberg',
        'Wien',
      ],
    },
  ];
}
